name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.2.2
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6.9.0
      with:
        context: ./src
        file: ./src/Dockerfile 
        push: true
        tags: |
          vento123/aula-primeira-pipeline:v${{ github.run_number }}
          vento123/aula-primeira-pipeline:latest
  CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v0.2.0
          with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            export_default_credentials: true

        - name: Configure kubectl
          run: |
            gcloud container clusters get-credentials app-01-cluster --zone us-west1-a --project cd-k8s-gcp-442415

        - name: Install gke-gcloud-auth-plugin
          run: |
            gcloud components install gke-gcloud-auth-plugin

        - name: Execução do Manifesto
          uses: Azure/k8s-deploy@v5
          with:
            manifests: |
              ./k8s/deployment.yaml
            images: |
              vento123/aula-primeira-pipeline:v${{ github.run_number }}