name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.2.2
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6.9.0
      with:
        context: ./src
        file: ./src/Dockerfile 
        push: true
        tags: |
          vento123/aula-primeira-pipeline:v${{ github.run_number }}
          vento123/aula-primeira-pipeline:latest
  CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
        # Download do código
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        # Configuração do kubeconfig
        - name: Configuração do contexto to kubernetes
          uses: azure/k8s-set-context@v4.0.0
          with:
              method: kubeconfig
              kubeconfig: ${{ secrets.K8S_CONFIG }}

        # Deploy no Kubernetes usando Azure K8s Deploy (kubectl apply)
        - name: Execução do Manifesto
          uses: Azure/k8s-deploy@v5
          with:
            manifests: |
              ./k8s/deployment.yaml
            images: |
              vento123/aula-primeira-pipeline:v${{ github.run_number }}